version: "3.9"

name: nuxt-course

services:
  postgres:
    container_name: postgress-nuxt
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 322
    ports:
      - "8888:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
